# theme: plainwhite
title: GWNU PRLab
author: KYL92
email: guy9284@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  GWNU-PRLab
show_excerpts: true # set to true to show excerpts on the homepage
future: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
# notion:
#   pages:
#     - id: 838177043c474405bcbc09826a13153b
  # databases:
  #   - id: 838177043c474405bcbc09826a13153b

plainwhite:
  name: GWNU-PRLab
  tagline: 국립강릉원주대학교 <br> 원주캠퍼스 <br> 컴퓨터공학과 <br> 패턴인식연구실
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  portfolio_image: "assets/Lab_logo.png" # the path from the base directory of the site to the image to display (no / at the start)
  lab_logo: "assets/images/logo.png" # the path to the lab logo image (optional)
  html_lang: "kr" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post
  # generate social links in footer
  social_links:
    # twitter: KYL92
    email: guy9284@gmail.com
    github:  KYL92
    youtube: /@user-jf9ru4vb3q
    # linkedIn: KYL92
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll

  navigation:
    - title: 연구실 소개
      url: "http://kyl92.github.io"
    - title: 주요 프로젝트
      url: "http://kyl92.github.io"
    - title: 성과 및 소식
      url: "http://kyl92.github.io"

plugins:
  - jekyll-seo-tag
